### ISSUE TITLE
Beautiful sorted SVG graphs

### ISSUE THREAD

**Issue by ebeshero** [lmcneil7/teen-titans#16]
Just a nag from your friendly neighborhood professor to make space for your beautiful sorted SVG graphs on the site! @lmcneil7 @smdunn921

**Comment by smdunn921** [comment]
Hey it's me. So, for the graphs:
1. did we want them to just produce the stats of the core teen titans unless an anomaly happens (such as, Slade talks the most in episode 13 like more than any of the titans)
2. do we want to include all of them or just the ones that really stand out. I have to edit them a bit, since the sizing is off on what I ran (especially in the ones that contain multiple different versions of the same character, but I can push up all the rough ones I have now

**Comment by smdunn921** [comment]
Hey it's me. So, for the graphs:

1. did we want them to just produce the stats of the core teen titans unless an anomaly happens (such as, Slade talks the most in episode 13 like more than any of the titans)
2. do we want to include all of them or just the ones that really stand out. I have to edit them a bit, since the sizing is off on what I ran (especially in the ones that contain multiple different versions of the same character, but I can push up all the rough ones I have now

@ebeshero @lmcneil7

**Comment by ebeshero** [comment]
@smdunn921 If size and space on the webpage is an issue, you could be selective and choose maybe the top 10 or top (whatever) of each episode to plot for "most talkative". 

You could experiment with resizing your graphs so we get a synoptic (holistic, big picture) view of all the most-talkative stats from the TV episodes on a screen...SVG can be writ small, but you'd want to make sure we can figure out which characters are being referenced at a glance. Hmmm. You could give the characters a set two-letter abbreviation to make their identity stand out in labels on your bar/lines... Just some design considerations for playing with lots of data!
