### ISSUE TITLE
XML Exercise 1 - Lauren McNeill

### ISSUE THREAD

**Issue by lmcneil7** [lmcneil7/teen-titans#19]
As you mentioned, I'm posting my file in the repo since it's HTML. For the exercise, I focused on fixing the methodology. I created two buttons using javascript to give the audience of the site a way to read about the parts that interest them. I didn't add more to the methodology yet, but I added another section for when I do that will focus on the fandom aspect.
[exercise1.zip](https://github.com/lmcneil7/teen-titans/files/4036815/exercise1.zip)

**Comment by frabbitry** [comment]
@lmcneil7 

Good work with XML exercise one! You've got a good start for thinking about how to appeal to two of your website audiences: the Teen Titans fandom and the Digital Humanities crowd interested in the coding process. 

Of course, the buttons don't do anything yet. I'd be interested to see how you decide to implement this idea, because there's a couple of directions that you could take. You could either show and hide different sections or jump down the page to different parts of the same methodology explanation, and either choice would imply a different assumption about how you think the users want to interact with your website. 

Showing and hiding might be easier to implement. [Here's](https://www.w3schools.com/howto/howto_js_toggle_hide_show.asp) a W3 tutorial that could give you a good start with it. 

I kind of like the idea of jumping down the page because it makes it less easy to ignore the fact that there's two sides to this project: a fandom side and a coding process side. Out of sight, out of mind, right? By keeping the coding process text visible on the page, the fandom people might be more likely to read it, and vice versa. I think that exposing people to new stuff is kind of cool, and I think that Digital Humanities projects offer us unique opportunities to connect worlds, if you will. 

If you would decide to do that, [some person on StackOverflow](https://stackoverflow.com/questions/13735912/anchor-jumping-by-using-javascript/13736194) offered an explanation for how to do it that could get you started. 

I'd be interested to see what you decide to do, and of course feel free to ping me with any questions.
