### ISSUE TITLE
schema revisions

### ISSUE THREAD

**Issue by lmcneil7** [lmcneil7/teen-titans#27]
I finalized the schema with a couple of new elements and attributes to fit the research question. It's pushed and ready to be looked at/associated with other episodes. I wrote comments directly to the schema and would like responses to the comments here to talk about anything that you're confused about or think we should change. Episode 1 is an example of what I'm imagining for the mark-up.

Fiona, it's ready to be looked at to see if it's a good schema! Your feedback is also appreciated. That's all I think.

**Comment by frabbitry** [comment]
So I'm going out to get a haircut and go to the Cheesecake Factory with my mother, but I will definitely take a look at the schema later today. Stay tuned for feedback...

**Comment by frabbitry** [comment]
@lmcneil7 Sorry for the delay, but I looked over your schema, and here's some feedback: 

1. I strongly STRONGLY encourage you to come up with a way to standardize locations, because it will make things MUCH easier when you go to map things. Come up with a list of all of the locations that are going to eventually be on the map and perhaps write them into the schema to enforce spelling etc. I know that you mentioned in a comment that you're not going to care about every single location, so your list doesn't have to be comprehensive in that regard. However, it should include all of the locations that you eventually want to end up on the map. Just speaking from experience, it's extremely frustrating when you run XQuery over your XML and your resulting CSV (or TSV... for Dr. B) files aren't accurate because someone misspelled a location name or used a different name to refer to the same place (you mentioned that some places have two names). If a location is ambiguous or project teammates can't decide on where a place actually is, then you can write that into the schema, if it's necessary. But ensuring that the location names, at least with regard to spelling, are standardized can save you a lot of trouble in the long run. 
2. I saw that you have a numbering system in place to indicate the number of movements each character made (at least that's what I took it to be? I could be wrong), and I was thinking that maybe you'd also want to include something to indicate WHERE the character moved TO. Just a thought. 
3. YES I would use refs for location (see point 1). 
4. As for your question at the end... why wouldn't you be allowed?

**Comment by lmcneil7** [comment]
@smdunn921 @amberpeddicord before I delete the comments on the schema, do you guys tag the word "Titans" or "Teen Titans" with the `char` element tag?

**Comment by lmcneil7** [comment]
comments from schema:
`#lm: do you put the word "Titans" in char?`
`#lm: shd said she was going to ask me about when to use this, so amp feel free to also ask!`
`#lm: It's for anything that can help with the creation of the map. The shot `attribute` is if it's a shot or just text like the old `annot` element.`
`#lm: should we leave the article in? for example, <location>the kitchen</location> or the <location>kitchen</location>`
`#lm: This is the system that I came up with to track movement. `mrkr` stands for marker, and is who is doing the action. `with` is an attribute to track who they are with in that location and `move` is to number their action. `move` is a numbering system and is to track their actions throughout the episode.`
`# TO EXPLAIN IT BETTER:`
`# *Each character needs an `action` element for each location they appear at. They only need another action element if they leave the location. `
`# *In some episodes, certain characters will have more actions. In episode 1, Starfire has five actions while the others only have three actions. This is so we know what we need to plot down for their routes. Since it was an alternate universe, I didn't track her movements with the future titans. I only indicated that she goes there and comes back.`
`# *`with` is going to be update constantly. At the moment, I have a basic tagging system, but it will need to be added to; for example, when three titans are traveling together instead of all. To add to it: Starfire is S, Robin is RB, Cyborg is C, Beast Boy is BB, and Raven is R. If they are traveling in a smaller group, then this is how you would do it: <action mrkr="Starfire" with="BB,R" move="1"/> implying that Starfire is with Beast Boy and Raven. As I mentioned, just add when you need it, so we don't have to do all possible combinations for no reason. It also offers information for analysis.`
`# You don't need to track their movement in large numbers. Meaning if they're in a over-arching location, don't record it multiple times. For example, in the Tower, we don't need to indicate when they're in their room or move into the living room unless there's another reason. I have an example in the first episode like that where Starfire only had one action in the Tower even though she started off in her room.`
`# *Any ideas to indicate the location in the action tag? I have one, but I want to see if anyone else has any ideas.`
`# *I also waited until their name showed up in a sd tag before putting the action tag down.`
`# *Some locations are referred by two different names, so I'm thinking we can add a ref tag to location to avoid confusion or another attribute with a similar purpose.`

**Comment by lmcneil7** [comment]
`#lm: question for fiona! i used a self closing tag for action, is that allowed?`

**Comment by amberpeddicord** [comment]
@lmcneil7 @smdunn921 So, in episode 11, there are a few spots where there are multiple speakers. Do we already have a way to handle this, or should I make changes to the schema?

**Comment by lmcneil7** [comment]
The schema already works for multiple speakers, so it would something like 
```xml
<spkr ref=“BeastBoy Cyborg>
```

**Comment by smdunn921** [comment]
@amberpeddicord i dont think lauren finished her thought? um but yea spkr+ is already a rule in there so you just need to put spaces in between them & they should pop up in the drop down menu. for example:
 `<sp><spkr ref="Robin BeastBoy Cyborg Raven">Robin, Beast Boy, Cyborg and Raven</spkr> NO!!</sp>`

**Comment by ebeshero** [comment]
Aha! I'm fixing @lmcneil7 's tick marks so this will show...

**Comment by ebeshero** [comment]
Fixed!
